steps:
    - name: 'gcr.io/cloud-builders/npm'
      args: ['install']
      dir: '.'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'lint']
      dir: '.'
    - name: 'gcr.io/cloud-builders/npm'
      args: ['run', 'build']
      dir: '.'
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'functions',
              'deploy',
              'bot-${_FUNCTION_NAME}',
              '--trigger-http',
              '--allow-unauthenticated',
              '--runtime',
              'nodejs12',
              '--region',
              'europe-west3',
              '--entry-point',
              'bot',
              '--memory',
              '128MB',
              '--set-env-vars',
              'BOT_TOKEN=${6701369024:AAFpB2-Vk4PhbV_TmwiQo-rp3zRLVUm6vTc},SHEET_ID=${0},SHEET_CLIENT_EMAIL=${iboxhdtv@gmail.com},SHEET_PRIVATE_KEY=${1nvBWxlOUyBQcYCycLitt9rPTPf7KPtFp1V17PmJWMF0},INSIDER_CHAT_ID=${-1001600833384}',
          ]
      dir: '.'
    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'functions',
              'deploy',
              'end-subscription-${_FUNCTION_NAME}',
              '--trigger-http',
              '--allow-unauthenticated',
              '--runtime',
              'nodejs12',
              '--region',
              'europe-west3',
              '--entry-point',
              'cancelSubscription',
              '--memory',
              '128MB',
              '--set-env-vars',
              'BOT_TOKEN=${_BOT_TOKEN},SHEET_ID=${_SHEET_ID},SHEET_CLIENT_EMAIL=${_SHEET_CLIENT_EMAIL},SHEET_PRIVATE_KEY=${_SHEET_PRIVATE_KEY},INSIDER_CHAT_ID=${_INSIDER_CHAT_ID}',
          ]
      dir: '.'

    - name: 'gcr.io/cloud-builders/gcloud'
      args:
          [
              'functions',
              'deploy',
              '${_REGISTER_FUNCTION_NAME}',
              '--trigger-http',
              '--allow-unauthenticated',
              '--runtime',
              'nodejs12',
              '--region',
              'europe-west3',
              '--entry-point',
              'register',
              '--memory',
              '128MB',
              '--set-env-vars',
              'BOT_TOKEN=${_BOT_TOKEN},SHEET_ID=${_SHEET_ID},SHEET_CLIENT_EMAIL=${_SHEET_CLIENT_EMAIL},SHEET_PRIVATE_KEY=${_SHEET_PRIVATE_KEY},INSIDER_CHAT_ID=${_INSIDER_CHAT_ID}',
          ]
      dir: '.'
